stages:
  - test

test:
  image: python:3.8
  before_script:
    - pip install --upgrade pip  # Met à jour pip
    - pip install -r requirements.txt
  script:
    - pytest
  only:
    - main  # Ou la branche de ton choix
