name: Python CI

on:
  push:
    branches:
      - main  # Ou la branche de ton choix (par exemple, "master")
  pull_request:
    branches:
      - main  # Ou la branche de ton choix

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Remplace par la version de Python que tu utilises

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt  # Assure-toi d'avoir un fichier requirements.txt avec toutes les dépendances

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest  # Exécute les tests
