name: Python CI

on:
  push:
    branches:
      - main  # Ou la branche de ton choix (par exemple, "master")
  pull_request:
    branches:
      - main  # Ou la branche de ton choix

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip  # Met à jour pip

    - name: Install dependencies
      run: |
        python -m venv venv  # Crée un environnement virtuel
        source venv/bin/activate  # Active l'environnement virtuel
        pip install -r requirements.txt  # Installe les dépendances depuis requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate  # Active l'environnement virtuel
        pytest  # Exécute les tests avec pytest
